version: "3"
services:
  gateway:
    image: nginx
    depends_on:
      - api
    ports:
      - "${CORELLE_HTTP_PORT:-5480}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Serve frontend directly (build happens locally)
      - frontend_dist:/frontend:ro
  api:
    build: .
    expose:
      - 5000
    depends_on:
      - database
    volumes:
      - ./data:/data:ro
  database:
    image: mdillon/postgis
    expose:
      - 5432
    ports:
      - "${CORELLE_DB_PORT:-54321}:5432"
    environment:
      - POSTGRES_DB=corelle
    volumes:
      - db_cluster:/var/lib/postgresql/data
  frontend:
    build: frontend
    volumes:
      - frontend_dist:/app/dist
      # This links the source files for the `corelle-client` lib,
      # so they don't have to be compiled.
      - ./corelle-client/src:/app/corelle-client
volumes:
  db_cluster:
  frontend_dist:
