version: "3"
services:
  gateway:
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "${CORELLE_HTTP_PORT}:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
  api:
    restart: unless-stopped
  database:
    restart: unless-stopped
  frontend:
    restart: unless-stopped
