version: "3"
services:
  gateway:
    restart: unless-stopped
    image: jonasal/nginx-certbot
    depends_on:
      - api
    ports:
      - "${CORELLE_HTTP_PORT}:80"
      - "${CORELLE_HTTPS_PORT}:443"
    environment:
      - CERTBOT_EMAIL
      # Substitute in value for SPARROW_DOMAIN
      # - CORELLE_DOMAIN
    volumes:
      # Swap out nginx conf for a certbot version
      - ./conf/nginx.certbot.conf:/etc/nginx/user_conf.d/site.conf:ro
  api:
    restart: unless-stopped
  database:
    restart: unless-stopped
  frontend:
    restart: unless-stopped
