version: "3"
services:
  frontend:
    build: frontend
    command: parcel watch index.html
    volumes:
      - node_modules:/app/node_modules
      - parcel_cache:/app/.cache
      # Mount code directory into container
      # for runtime code modification
      - ./frontend:/app
volumes:
  node_modules:
  parcel_cache:
