[tool.poetry]
authors = ["Daven Quinn <dev@davenquinn.com>"]
description = ""
name = "corelle"
version = "0.1.0"

[tool.poetry.dependencies]
Fiona = "^1.8.19"
Flask = "^1.1.2"
Flask-RESTful = "^0.3.8"
PyYAML = "^5.4.1"
click = "^7.1.2"
ipython = "^7.22.0"
numpy = "^1.20.2"
numpy-quaternion = "^2021.4.5"
pg-viewtils = {url = "https://github.com/davenquinn/pg-viewtils/archive/master.zip"}
psycopg2-binary = "^2.8.6"
python = "^3.8"
simplejson = "^3.17.2"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
corelle = 'corelle.cli:cli'

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
