[project]
name = "corelle.engine"
version = "2.1.0-dev2"
description = "An API server application for the Corelle plate-rotation system"
authors = [{ name = "Daven Quinn", email = "dev@davenquinn.com" }]
requires-python = ">=3.10,<4"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "Fiona>=1.10.1,<2",
    "IPython>=8.0,<10",
    "PyYAML>=6.0,<7",
    "corelle.client",
    "macrostrat.database>=4.0.0,<5",
    "macrostrat.utils>=1.0.1,<2",
    "numba>=0.63.1,<0.66",
    "numpy>=2.0.0,<3",
    "numpy-quaternion>=2024.0.13,<2025.0.0",
    "rich>12.6.0,<15.0.0",
    "typer>0.12.0,<0.26",
    "wget>=3.2,<4",
    "geoalchemy2>0.14.0,<0.20.0",
    "python-dotenv>=1.2.2",
]

[project.scripts]
corelle = "corelle.engine:cli"

[dependency-groups]
dev = []

[tool.uv]

[tool.uv.sources]
"corelle.client" = { path = "../client", editable = true }

[tool.uv.build-backend]
module-name = ["corelle"]
module-root = ""
namespace = true

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"
